-- =============================================================================
-- EDUCATION - MIGRATION V10: PHIEU HOC PHI DIEN TU + VIETQR
--
-- Cot ky thu tren FIN_TUITION_FEES, quy luat ma HP, procedure PRC_GET_TUITION_SLIP_DATA.
--
--   sqlplus EDUCATION/EDUCATION@//localhost:1521/ORCL @V10__tuition_slip.sql
-- =============================================================================

SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED

PROMPT ============ V10.1 Cot phieu hoc phi ============

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE FIN_TUITION_FEES ADD FEE_MONTH NUMBER(2)';
    DBMS_OUTPUT.PUT_LINE('FIN_TUITION_FEES.FEE_MONTH: added');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE IN (-1430, -01430) THEN
            DBMS_OUTPUT.PUT_LINE('FIN_TUITION_FEES.FEE_MONTH: already exists');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE FIN_TUITION_FEES ADD FEE_YEAR NUMBER(4)';
    DBMS_OUTPUT.PUT_LINE('FIN_TUITION_FEES.FEE_YEAR: added');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE IN (-1430, -01430) THEN
            DBMS_OUTPUT.PUT_LINE('FIN_TUITION_FEES.FEE_YEAR: already exists');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE FIN_TUITION_FEES ADD PRICE_PER_SESSION NUMBER(15,2)';
    DBMS_OUTPUT.PUT_LINE('FIN_TUITION_FEES.PRICE_PER_SESSION: added');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE IN (-1430, -01430) THEN
            DBMS_OUTPUT.PUT_LINE('FIN_TUITION_FEES.PRICE_PER_SESSION: already exists');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE FIN_TUITION_FEES ADD TOTAL_SESSIONS NUMBER(10)';
    DBMS_OUTPUT.PUT_LINE('FIN_TUITION_FEES.TOTAL_SESSIONS: added');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE IN (-1430, -01430) THEN
            DBMS_OUTPUT.PUT_LINE('FIN_TUITION_FEES.TOTAL_SESSIONS: already exists');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE FIN_TUITION_FEES ADD TEACHER_COMMENT VARCHAR2(1000)';
    DBMS_OUTPUT.PUT_LINE('FIN_TUITION_FEES.TEACHER_COMMENT: added');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE IN (-1430, -01430) THEN
            DBMS_OUTPUT.PUT_LINE('FIN_TUITION_FEES.TEACHER_COMMENT: already exists');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE FIN_TUITION_FEES ADD FOOTER_WISH VARCHAR2(500)';
    DBMS_OUTPUT.PUT_LINE('FIN_TUITION_FEES.FOOTER_WISH: added');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE IN (-1430, -01430) THEN
            DBMS_OUTPUT.PUT_LINE('FIN_TUITION_FEES.FOOTER_WISH: already exists');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE q'[ALTER TABLE FIN_TUITION_FEES ADD SLIP_LABEL VARCHAR2(50) DEFAULT 'Mặc Định']';
    DBMS_OUTPUT.PUT_LINE('FIN_TUITION_FEES.SLIP_LABEL: added');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE IN (-1430, -01430) THEN
            DBMS_OUTPUT.PUT_LINE('FIN_TUITION_FEES.SLIP_LABEL: already exists');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE q'[ALTER TABLE FIN_TUITION_FEES ADD CONSTRAINT CK_FEES_MONTH CHECK (FEE_MONTH IS NULL OR FEE_MONTH BETWEEN 1 AND 12)]';
    DBMS_OUTPUT.PUT_LINE('CK_FEES_MONTH: added');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE IN (-2260, -02275, -02260) THEN
            DBMS_OUTPUT.PUT_LINE('CK_FEES_MONTH: already exists');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE q'[ALTER TABLE FIN_TUITION_FEES ADD CONSTRAINT CK_FEES_YEAR CHECK (FEE_YEAR IS NULL OR FEE_YEAR BETWEEN 2000 AND 2100)]';
    DBMS_OUTPUT.PUT_LINE('CK_FEES_YEAR: added');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE IN (-2260, -02275, -02260) THEN
            DBMS_OUTPUT.PUT_LINE('CK_FEES_YEAR: already exists');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE q'[ALTER TABLE FIN_TUITION_FEES ADD CONSTRAINT CK_FEES_SESSIONS CHECK (TOTAL_SESSIONS IS NULL OR TOTAL_SESSIONS >= 0)]';
    DBMS_OUTPUT.PUT_LINE('CK_FEES_SESSIONS: added');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE IN (-2260, -02275, -02260) THEN
            DBMS_OUTPUT.PUT_LINE('CK_FEES_SESSIONS: already exists');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE q'[ALTER TABLE FIN_TUITION_FEES ADD CONSTRAINT CK_FEES_PRICE_SESSION CHECK (PRICE_PER_SESSION IS NULL OR PRICE_PER_SESSION >= 0)]';
    DBMS_OUTPUT.PUT_LINE('CK_FEES_PRICE_SESSION: added');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE IN (-2260, -02275, -02260) THEN
            DBMS_OUTPUT.PUT_LINE('CK_FEES_PRICE_SESSION: already exists');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE UNIQUE INDEX UQ_FEES_MONTHLY ON FIN_TUITION_FEES (
            CASE WHEN IS_DELETED = 0 AND FEE_YEAR IS NOT NULL AND FEE_MONTH IS NOT NULL THEN STUDENT_ID END,
            CASE WHEN IS_DELETED = 0 AND FEE_YEAR IS NOT NULL AND FEE_MONTH IS NOT NULL THEN CLASS_ID END,
            CASE WHEN IS_DELETED = 0 AND FEE_YEAR IS NOT NULL AND FEE_MONTH IS NOT NULL THEN FEE_YEAR END,
            CASE WHEN IS_DELETED = 0 AND FEE_YEAR IS NOT NULL AND FEE_MONTH IS NOT NULL THEN FEE_MONTH END
        )
    ]';
    DBMS_OUTPUT.PUT_LINE('UQ_FEES_MONTHLY: added');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE IN (-955, -01408) THEN
            DBMS_OUTPUT.PUT_LINE('UQ_FEES_MONTHLY: already exists');
        ELSE
            RAISE;
        END IF;
END;
/

COMMENT ON COLUMN FIN_TUITION_FEES.FEE_MONTH IS 'Ky thu: thang 1-12 cua phieu hoc phi';
COMMENT ON COLUMN FIN_TUITION_FEES.FEE_YEAR IS 'Ky thu: nam YYYY';
COMMENT ON COLUMN FIN_TUITION_FEES.PRICE_PER_SESSION IS 'Don gia hoc phi / 1 buoi';
COMMENT ON COLUMN FIN_TUITION_FEES.TOTAL_SESSIONS IS 'So buoi PRESENT trong ky';
COMMENT ON COLUMN FIN_TUITION_FEES.TEACHER_COMMENT IS 'Nhan xet giao vien in tren phieu';
COMMENT ON COLUMN FIN_TUITION_FEES.FOOTER_WISH IS 'Loi chuc cuoi phieu';
COMMENT ON COLUMN FIN_TUITION_FEES.SLIP_LABEL IS 'The phan loai (vi du: Mac Dinh)';

PROMPT ============ V10.2 SYS_CODE_RULES TUITION ============

MERGE INTO SYS_CODE_RULES t
USING (
    SELECT 'TUITION' AS RULE_CODE,
           'FINANCE' AS MODULE_NAME,
           'FIN_TUITION_FEES' AS TABLE_NAME,
           'HP' AS PREFIX,
           '{PREFIX}{YYYY}{MM}{SEQ}' AS PATTERN,
           4 AS SEQ_LENGTH,
           'MONTH' AS RESET_CYCLE
      FROM DUAL
) s
ON (t.RULE_CODE = s.RULE_CODE)
WHEN MATCHED THEN
    UPDATE SET t.PATTERN = s.PATTERN,
               t.PREFIX = s.PREFIX,
               t.SEQ_LENGTH = s.SEQ_LENGTH,
               t.RESET_CYCLE = s.RESET_CYCLE,
               t.IS_ACTIVE = 1,
               t.IS_DELETED = 0,
               t.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN
    INSERT (ID, RULE_CODE, MODULE_NAME, TABLE_NAME, PREFIX, PATTERN, SEQ_LENGTH, RESET_CYCLE,
            LAST_RESET_KEY, LAST_SEQ, IS_ACTIVE, IS_DELETED, CREATED_AT)
    VALUES (SEQ_SYS_CODE_RULES.NEXTVAL, s.RULE_CODE, s.MODULE_NAME, s.TABLE_NAME, s.PREFIX,
            s.PATTERN, s.SEQ_LENGTH, s.RESET_CYCLE, NULL, 0, 1, 0, SYSTIMESTAMP);

PROMPT SYS_CODE_RULES TUITION: OK

PROMPT ============ V10.3 Trigger ma khoan phi ============

CREATE OR REPLACE TRIGGER TRG_FIN_TUITION_FEES_BI_CODE
BEFORE INSERT ON FIN_TUITION_FEES
FOR EACH ROW
BEGIN
    IF :NEW.FEE_CODE IS NULL OR TRIM(:NEW.FEE_CODE) IS NULL THEN
        :NEW.FEE_CODE := FN_NEXT_BIZ_CODE('TUITION');
    END IF;
END;
/

PROMPT Trigger TRG_FIN_TUITION_FEES_BI_CODE: OK

PROMPT ============ V10.4 PRC_GET_TUITION_SLIP_DATA ============

CREATE OR REPLACE PROCEDURE PRC_GET_TUITION_SLIP_DATA(
    P_INVOICE_ID        IN  NUMBER,
    O_INFO_CURSOR       OUT SYS_REFCURSOR,
    O_ATTENDANCE_CURSOR OUT SYS_REFCURSOR,
    O_ERR_CODE          OUT VARCHAR2,
    O_ERR_MSG           OUT VARCHAR2
) AS
    V_EXISTS NUMBER;
    V_MONTH  NUMBER(2);
    V_YEAR   NUMBER(4);
    V_CLASS  NUMBER(19);
    V_STUD   NUMBER(19);
BEGIN
    IF P_INVOICE_ID IS NULL THEN
        O_ERR_CODE := 'FEE_ID_REQUIRED';
        O_ERR_MSG  := 'Thieu ID khoan hoc phi.';
        RETURN;
    END IF;

    SELECT COUNT(*)
      INTO V_EXISTS
      FROM FIN_TUITION_FEES
     WHERE ID = P_INVOICE_ID
       AND IS_DELETED = 0;

    IF V_EXISTS = 0 THEN
        O_ERR_CODE := 'FEE_NOT_FOUND';
        O_ERR_MSG  := 'Khong tim thay khoan hoc phi ID: ' || P_INVOICE_ID;
        RETURN;
    END IF;

    SELECT NVL(f.FEE_MONTH, EXTRACT(MONTH FROM NVL(f.DUE_DATE, f.CREATED_AT))),
           NVL(f.FEE_YEAR,  EXTRACT(YEAR  FROM NVL(f.DUE_DATE, f.CREATED_AT))),
           f.CLASS_ID,
           f.STUDENT_ID
      INTO V_MONTH, V_YEAR, V_CLASS, V_STUD
      FROM FIN_TUITION_FEES f
     WHERE f.ID = P_INVOICE_ID
       AND f.IS_DELETED = 0;

    OPEN O_INFO_CURSOR FOR
        SELECT f.ID,
               f.FEE_CODE,
               V_MONTH AS FEE_MONTH,
               V_YEAR  AS FEE_YEAR,
               f.CLASS_ID,
               c.CLASS_CODE,
               c.CLASS_NAME,
               f.STUDENT_ID,
               s.STUDENT_CODE,
               s.FULL_NAME AS STUDENT_NAME,
               f.PRICE_PER_SESSION,
               f.TOTAL_SESSIONS,
               f.TOTAL_AMOUNT,
               f.DISCOUNT_AMOUNT,
               f.PAID_AMOUNT,
               (f.TOTAL_AMOUNT - f.DISCOUNT_AMOUNT - f.PAID_AMOUNT) AS REMAINING_AMOUNT,
               f.TEACHER_COMMENT,
               f.FOOTER_WISH,
               NVL(f.SLIP_LABEL, 'Mặc Định') AS SLIP_LABEL,
               f.STATUS,
               f.DUE_DATE
          FROM FIN_TUITION_FEES f
          JOIN EDU_STUDENTS s ON s.ID = f.STUDENT_ID
          LEFT JOIN EDU_CLASSES c ON c.ID = f.CLASS_ID
         WHERE f.ID = P_INVOICE_ID
           AND f.IS_DELETED = 0;

    OPEN O_ATTENDANCE_CURSOR FOR
        SELECT a.ATTENDANCE_DATE
          FROM EDU_ATTENDANCE a
         WHERE a.IS_DELETED = 0
           AND a.STATUS = 'PRESENT'
           AND a.STUDENT_ID = V_STUD
           AND (V_CLASS IS NULL OR a.CLASS_ID = V_CLASS)
           AND EXTRACT(MONTH FROM a.ATTENDANCE_DATE) = V_MONTH
           AND EXTRACT(YEAR  FROM a.ATTENDANCE_DATE) = V_YEAR
         ORDER BY a.ATTENDANCE_DATE ASC, a.ID ASC;

    O_ERR_CODE := '0';
    O_ERR_MSG  := 'SUCCESS';
EXCEPTION
    WHEN OTHERS THEN
        IF O_INFO_CURSOR IS NOT NULL AND O_INFO_CURSOR%ISOPEN THEN CLOSE O_INFO_CURSOR; END IF;
        IF O_ATTENDANCE_CURSOR IS NOT NULL AND O_ATTENDANCE_CURSOR%ISOPEN THEN CLOSE O_ATTENDANCE_CURSOR; END IF;
        O_ERR_CODE := TO_CHAR(SQLCODE);
        O_ERR_MSG  := SUBSTR(SQLERRM, 1, 255);
END PRC_GET_TUITION_SLIP_DATA;
/

PROMPT PRC_GET_TUITION_SLIP_DATA: OK
PROMPT ============ V10 DONE ============
/