-- =============================================================================
-- EDUCATION - MIGRATION V11: SO TAI KHOAN NGAN HANG (VietQR)
--
-- Chi 1 STK IS_ACTIVE = 1 tai moi thoi diem (unique function-based index).
--
--   sqlplus EDUCATION/EDUCATION@//localhost:1521/ORCL @V11__bank_accounts.sql
-- =============================================================================

SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED

PROMPT ============ V11.1 Sequence + bang FIN_BANK_ACCOUNTS ============

BEGIN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_FIN_BANK_ACCOUNTS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE';
    DBMS_OUTPUT.PUT_LINE('SEQ_FIN_BANK_ACCOUNTS: created');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            DBMS_OUTPUT.PUT_LINE('SEQ_FIN_BANK_ACCOUNTS: already exists');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE FIN_BANK_ACCOUNTS (
            ID            NUMBER(19)    NOT NULL,
            ACCOUNT_CODE  VARCHAR2(30)  NOT NULL,
            BANK_BIN      VARCHAR2(20)  NOT NULL,
            BANK_NAME     VARCHAR2(100) NOT NULL,
            ACCOUNT_NO    VARCHAR2(30)  NOT NULL,
            ACCOUNT_NAME  VARCHAR2(150) NOT NULL,
            IS_ACTIVE     NUMBER(1)     DEFAULT 0 NOT NULL,
            NOTE          VARCHAR2(255),
            IS_DELETED    NUMBER(1)     DEFAULT 0 NOT NULL,
            CREATED_AT    TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP NOT NULL,
            UPDATED_AT    TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP,
            CREATED_BY    VARCHAR2(50),
            UPDATED_BY    VARCHAR2(50),
            CONSTRAINT PK_FIN_BANK_ACCOUNTS PRIMARY KEY (ID),
            CONSTRAINT CK_BANK_ACCT_DELETED CHECK (IS_DELETED IN (0, 1)),
            CONSTRAINT CK_BANK_ACCT_ACTIVE CHECK (IS_ACTIVE IN (0, 1))
        )
    ]';
    DBMS_OUTPUT.PUT_LINE('FIN_BANK_ACCOUNTS: created');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            DBMS_OUTPUT.PUT_LINE('FIN_BANK_ACCOUNTS: already exists');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE UNIQUE INDEX UQ_BANK_ACCT_CODE ON FIN_BANK_ACCOUNTS (
            CASE WHEN IS_DELETED = 0 THEN ACCOUNT_CODE END
        )
    ]';
    DBMS_OUTPUT.PUT_LINE('UQ_BANK_ACCT_CODE: created');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE IN (-955, -01408) THEN
            DBMS_OUTPUT.PUT_LINE('UQ_BANK_ACCT_CODE: already exists');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE UNIQUE INDEX UQ_BANK_ACCT_ONE_ACTIVE ON FIN_BANK_ACCOUNTS (
            CASE WHEN IS_DELETED = 0 AND IS_ACTIVE = 1 THEN 1 END
        )
    ]';
    DBMS_OUTPUT.PUT_LINE('UQ_BANK_ACCT_ONE_ACTIVE: created');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE IN (-955, -01408) THEN
            DBMS_OUTPUT.PUT_LINE('UQ_BANK_ACCT_ONE_ACTIVE: already exists');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE UNIQUE INDEX UQ_BANK_ACCT_NO ON FIN_BANK_ACCOUNTS (
            CASE WHEN IS_DELETED = 0 THEN BANK_BIN END,
            CASE WHEN IS_DELETED = 0 THEN ACCOUNT_NO END
        )
    ]';
    DBMS_OUTPUT.PUT_LINE('UQ_BANK_ACCT_NO: created');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE IN (-955, -01408) THEN
            DBMS_OUTPUT.PUT_LINE('UQ_BANK_ACCT_NO: already exists');
        ELSE
            RAISE;
        END IF;
END;
/

COMMENT ON TABLE FIN_BANK_ACCOUNTS IS 'Danh muc so tai khoan thu huong VietQR; chi 1 dong IS_ACTIVE=1';
COMMENT ON COLUMN FIN_BANK_ACCOUNTS.IS_ACTIVE IS '1 = dang su dung de sinh QR/phieu hoc phi; toi da 1 dong';

PROMPT ============ V11.2 Seed STK mac dinh ============

MERGE INTO FIN_BANK_ACCOUNTS t
USING (
    SELECT 'BA-DEFAULT' AS ACCOUNT_CODE,
           '970436' AS BANK_BIN,
           'Vietcombank' AS BANK_NAME,
           '1234567890' AS ACCOUNT_NO,
           'TRUONG EDUCATION' AS ACCOUNT_NAME
      FROM DUAL
) s ON (t.ACCOUNT_CODE = s.ACCOUNT_CODE)
WHEN MATCHED THEN
    UPDATE SET t.BANK_BIN = s.BANK_BIN,
               t.BANK_NAME = s.BANK_NAME,
               t.ACCOUNT_NO = s.ACCOUNT_NO,
               t.ACCOUNT_NAME = s.ACCOUNT_NAME,
               t.IS_DELETED = 0
WHEN NOT MATCHED THEN
    INSERT (ID, ACCOUNT_CODE, BANK_BIN, BANK_NAME, ACCOUNT_NO, ACCOUNT_NAME,
            IS_ACTIVE, IS_DELETED, CREATED_AT, CREATED_BY)
    VALUES (SEQ_FIN_BANK_ACCOUNTS.NEXTVAL, s.ACCOUNT_CODE, s.BANK_BIN, s.BANK_NAME,
            s.ACCOUNT_NO, s.ACCOUNT_NAME, 0, 0, SYSTIMESTAMP, 'V11_MIGRATION');

-- Dam bao dung 1 STK active: neu seed da co nhung khong co dong active, bat BA-DEFAULT.
UPDATE FIN_BANK_ACCOUNTS
   SET IS_ACTIVE = 1,
       UPDATED_AT = SYSTIMESTAMP
 WHERE ACCOUNT_CODE = 'BA-DEFAULT'
   AND IS_DELETED = 0
   AND NOT EXISTS (
           SELECT 1 FROM FIN_BANK_ACCOUNTS a
            WHERE a.IS_DELETED = 0 AND a.IS_ACTIVE = 1
       );

PROMPT ============ V11.3 Menu Cau hinh STK ============

MERGE INTO SYS_MENUS t
USING (
    SELECT 305 ID, 300 PARENT_ID, 'MENU_BANK_ACCOUNT' MENU_CODE,
           'Tài khoản thụ hưởng' MENU_NAME, '/system/bank-accounts' PATH,
           'building-columns' ICON, 5 SORT_ORDER
      FROM DUAL
) s ON (t.MENU_CODE = s.MENU_CODE)
WHEN MATCHED THEN UPDATE SET t.PARENT_ID = s.PARENT_ID, t.MENU_NAME = s.MENU_NAME, t.PATH = s.PATH,
                             t.ICON = s.ICON, t.SORT_ORDER = s.SORT_ORDER, t.MENU_TYPE = 'MENU',
                             t.IS_DELETED = 0, t.STATUS = 'ACTIVE'
WHEN NOT MATCHED THEN INSERT (ID, PARENT_ID, MENU_CODE, MENU_NAME, MENU_TYPE, PATH, ICON, SORT_ORDER,
                              IS_HIDDEN, STATUS, IS_DELETED, CREATED_BY)
                      VALUES (s.ID, s.PARENT_ID, s.MENU_CODE, s.MENU_NAME, 'MENU', s.PATH, s.ICON, s.SORT_ORDER,
                              0, 'ACTIVE', 0, 'V11_MIGRATION');

MERGE INTO SYS_FUNCTIONS t
USING (
    SELECT m.ID AS MENU_ID, x.FUNCTION_CODE, x.FUNCTION_NAME
      FROM SYS_MENUS m
      JOIN (
            SELECT 'VIEW' FUNCTION_CODE, 'Xem danh sách' FUNCTION_NAME FROM DUAL UNION ALL
            SELECT 'CREATE', 'Thêm mới' FROM DUAL UNION ALL
            SELECT 'UPDATE', 'Cập nhật' FROM DUAL UNION ALL
            SELECT 'DELETE', 'Xóa' FROM DUAL
           ) x ON 1 = 1
     WHERE m.MENU_CODE = 'MENU_BANK_ACCOUNT'
       AND m.IS_DELETED = 0
) s ON (t.MENU_ID = s.MENU_ID AND t.FUNCTION_CODE = s.FUNCTION_CODE)
WHEN MATCHED THEN UPDATE SET t.FUNCTION_NAME = s.FUNCTION_NAME, t.IS_DELETED = 0
WHEN NOT MATCHED THEN INSERT (ID, MENU_ID, FUNCTION_CODE, FUNCTION_NAME, IS_DELETED)
                      VALUES (SEQ_SYS_FUNCTIONS.NEXTVAL, s.MENU_ID, s.FUNCTION_CODE, s.FUNCTION_NAME, 0);

MERGE INTO SYS_ROLE_MENU_PERMISSIONS t
USING (
    SELECT r.ID AS ROLE_ID,
           f.MENU_ID,
           LISTAGG(f.FUNCTION_CODE, ',') WITHIN GROUP (ORDER BY f.ID) AS ALLOWED_FUNCTIONS
      FROM SYS_FUNCTIONS f
      JOIN SYS_MENUS m ON m.ID = f.MENU_ID AND m.MENU_CODE = 'MENU_BANK_ACCOUNT' AND m.IS_DELETED = 0
      CROSS JOIN SYS_ROLES r
     WHERE r.ROLE_CODE = 'ROLE_ADMIN'
       AND f.IS_DELETED = 0
     GROUP BY r.ID, f.MENU_ID
) s ON (t.ROLE_ID = s.ROLE_ID AND t.MENU_ID = s.MENU_ID)
WHEN MATCHED THEN UPDATE SET t.ALLOWED_FUNCTIONS = s.ALLOWED_FUNCTIONS
WHEN NOT MATCHED THEN INSERT (ID, ROLE_ID, MENU_ID, ALLOWED_FUNCTIONS, CREATED_BY)
                      VALUES (SEQ_SYS_ROLE_MENU_PERM.NEXTVAL, s.ROLE_ID, s.MENU_ID, s.ALLOWED_FUNCTIONS, 'V11_MIGRATION');

MERGE INTO SYS_ROLE_MENU_PERMISSIONS t
USING (
    SELECT r.ID AS ROLE_ID, m.ID AS MENU_ID, 'VIEW,CREATE,UPDATE,DELETE' AS ALLOWED_FUNCTIONS
      FROM SYS_ROLES r
      JOIN SYS_MENUS m ON m.MENU_CODE = 'MENU_BANK_ACCOUNT' AND m.IS_DELETED = 0
     WHERE r.ROLE_CODE = 'ROLE_ACCOUNTANT'
) s ON (t.ROLE_ID = s.ROLE_ID AND t.MENU_ID = s.MENU_ID)
WHEN MATCHED THEN UPDATE SET t.ALLOWED_FUNCTIONS = s.ALLOWED_FUNCTIONS
WHEN NOT MATCHED THEN INSERT (ID, ROLE_ID, MENU_ID, ALLOWED_FUNCTIONS, CREATED_BY)
                      VALUES (SEQ_SYS_ROLE_MENU_PERM.NEXTVAL, s.ROLE_ID, s.MENU_ID, s.ALLOWED_FUNCTIONS, 'V11_MIGRATION');

COMMIT;

PROMPT ============ V11 DONE ============
EXIT

