-- =============================================================================
-- EDUCATION - MIGRATION V18_2: MENU "THONG BAO" (MENU_ANNOUNCEMENT)
--
-- Giai doan 1, Stream B (feat/portal-p1-announce). CHI Stream B sua file nay.
--
-- Script nay lam:
--   V18_2.1 Kiem tra truoc: DIR_ACADEMIC, ROLE_ADMIN, ROLE_TEACHER.
--   V18_2.2 Menu MENU_ANNOUNCEMENT ('Thong bao', /academic/announcements) duoi DIR_ACADEMIC.
--   V18_2.3 Chuc nang: VIEW / CREATE / UPDATE / DELETE / PUBLISH
--           (backend: Permissions.ANNOUNCEMENT_*).
--   V18_2.4 Phan quyen: ROLE_ADMIN toan quyen; ROLE_TEACHER VIEW/CREATE/UPDATE/PUBLISH
--           (giong pattern diem danh / diem - giao vien tao noi dung, khong DELETE).
--   V18_2.5 Kiem tra sau (ke ca ten menu UNISTR).
--
-- QUY UOC:
--   * WHENEVER SQLERROR EXIT ... ROLLBACK; ket thuc bang COMMIT + EXIT.
--   * Chay lai an toan: MERGE ON (MENU_CODE) / (MENU_ID, FUNCTION_CODE) / (ROLE_ID, MENU_ID);
--     ID tu SEQ_SYS_MENUS / SEQ_SYS_FUNCTIONS / SEQ_SYS_ROLE_MENU_PERM.
--   * Chi DML, khong DDL.
--   * MENU_NAME / FUNCTION_NAME dung UNISTR(...) - khong phu thuoc NLS_LANG.
--
-- THU TU CHAY: sau V18_1.
--
--   sqlplus EDUCATION/EDUCATION@//localhost:1521/ORCL @src/main/resources/db/migration/V18_2__announcement_menus.sql
--
-- ROLLBACK:
--   DELETE FROM SYS_ROLE_MENU_PERMISSIONS
--    WHERE MENU_ID IN (SELECT ID FROM SYS_MENUS WHERE MENU_CODE = 'MENU_ANNOUNCEMENT');
--   UPDATE SYS_FUNCTIONS SET IS_DELETED = 1, UPDATED_AT = SYSTIMESTAMP
--    WHERE MENU_ID IN (SELECT ID FROM SYS_MENUS WHERE MENU_CODE = 'MENU_ANNOUNCEMENT');
--   UPDATE SYS_MENUS SET IS_DELETED = 1, IS_HIDDEN = 1, UPDATED_AT = SYSTIMESTAMP, UPDATED_BY = 'V18_2_ROLLBACK'
--    WHERE MENU_CODE = 'MENU_ANNOUNCEMENT';
--   COMMIT;
-- =============================================================================

WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED

PROMPT V18_2: NLS_LANG=AMERICAN_AMERICA.AL32UTF8 khuyen nghi (khong bat buoc - seed dung UNISTR)

PROMPT ============ V18_2.1 Kiem tra truoc ============

DECLARE
    V_COUNT NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_COUNT FROM SYS_MENUS WHERE MENU_CODE = 'DIR_ACADEMIC' AND IS_DELETED = 0;
    IF V_COUNT <> 1 THEN
        RAISE_APPLICATION_ERROR(-20001, 'V18_2: khong tim thay thu muc DIR_ACADEMIC');
    END IF;
    SELECT COUNT(*) INTO V_COUNT FROM SYS_ROLES WHERE ROLE_CODE = 'ROLE_ADMIN' AND IS_DELETED = 0;
    IF V_COUNT <> 1 THEN
        RAISE_APPLICATION_ERROR(-20002, 'V18_2: khong tim thay vai tro ROLE_ADMIN');
    END IF;
    SELECT COUNT(*) INTO V_COUNT FROM SYS_ROLES WHERE ROLE_CODE = 'ROLE_TEACHER' AND IS_DELETED = 0;
    IF V_COUNT <> 1 THEN
        RAISE_APPLICATION_ERROR(-20003, 'V18_2: khong tim thay vai tro ROLE_TEACHER');
    END IF;
    DBMS_OUTPUT.PUT_LINE('  DIR_ACADEMIC, ROLE_ADMIN, ROLE_TEACHER  OK');
END;
/

PROMPT ============ V18_2.2 Menu MENU_ANNOUNCEMENT ============

MERGE INTO SYS_MENUS t
USING (
    SELECT x.MENU_CODE, x.MENU_NAME, x.PATH, x.ICON, x.SORT_ORDER, p.ID PARENT_ID
      FROM (
            SELECT 'MENU_ANNOUNCEMENT' MENU_CODE, UNISTR('Th\00F4ng b\00E1o') MENU_NAME,
                   '/academic/announcements' PATH, 'bullhorn' ICON, 6 SORT_ORDER FROM DUAL
           ) x
      JOIN SYS_MENUS p ON p.MENU_CODE = 'DIR_ACADEMIC' AND p.IS_DELETED = 0
) s ON (t.MENU_CODE = s.MENU_CODE)
WHEN MATCHED THEN UPDATE SET t.PARENT_ID = s.PARENT_ID, t.MENU_NAME = s.MENU_NAME, t.PATH = s.PATH,
                             t.ICON = s.ICON, t.SORT_ORDER = s.SORT_ORDER, t.MENU_TYPE = 'MENU',
                             t.IS_HIDDEN = 0, t.IS_DELETED = 0, t.STATUS = 'ACTIVE',
                             t.UPDATED_AT = SYSTIMESTAMP, t.UPDATED_BY = 'V18_2_MIGRATION'
WHEN NOT MATCHED THEN INSERT (ID, PARENT_ID, MENU_CODE, MENU_NAME, MENU_TYPE, PATH, ICON, SORT_ORDER,
                              IS_HIDDEN, STATUS, IS_DELETED, CREATED_BY)
                      VALUES (SEQ_SYS_MENUS.NEXTVAL, s.PARENT_ID, s.MENU_CODE, s.MENU_NAME, 'MENU', s.PATH, s.ICON,
                              s.SORT_ORDER, 0, 'ACTIVE', 0, 'V18_2_MIGRATION');

PROMPT ============ V18_2.3 Chuc nang ============

MERGE INTO SYS_FUNCTIONS t
USING (
    SELECT m.ID AS MENU_ID, x.FUNCTION_CODE, x.FUNCTION_NAME
      FROM SYS_MENUS m
      JOIN (
            SELECT 'VIEW' FUNCTION_CODE, UNISTR('Xem danh s\00E1ch') FUNCTION_NAME FROM DUAL UNION ALL
            SELECT 'CREATE', UNISTR('Th\00EAm m\1EDBi') FROM DUAL UNION ALL
            SELECT 'UPDATE', UNISTR('C\1EADp nh\1EADt') FROM DUAL UNION ALL
            SELECT 'DELETE', UNISTR('X\00F3a') FROM DUAL UNION ALL
            SELECT 'PUBLISH', UNISTR('Xu\1EA5t b\1EA3n') FROM DUAL
           ) x ON 1 = 1
     WHERE m.MENU_CODE = 'MENU_ANNOUNCEMENT'
       AND m.IS_DELETED = 0
) s ON (t.MENU_ID = s.MENU_ID AND t.FUNCTION_CODE = s.FUNCTION_CODE)
WHEN MATCHED THEN UPDATE SET t.FUNCTION_NAME = s.FUNCTION_NAME, t.IS_DELETED = 0
WHEN NOT MATCHED THEN INSERT (ID, MENU_ID, FUNCTION_CODE, FUNCTION_NAME, IS_DELETED)
                      VALUES (SEQ_SYS_FUNCTIONS.NEXTVAL, s.MENU_ID, s.FUNCTION_CODE, s.FUNCTION_NAME, 0);

PROMPT ============ V18_2.4 Phan quyen ROLE_ADMIN + ROLE_TEACHER ============

MERGE INTO SYS_ROLE_MENU_PERMISSIONS t
USING (
    SELECT r.ID AS ROLE_ID,
           f.MENU_ID,
           LISTAGG(f.FUNCTION_CODE, ',') WITHIN GROUP (ORDER BY f.ID) AS ALLOWED_FUNCTIONS
      FROM SYS_FUNCTIONS f
      JOIN SYS_MENUS m ON m.ID = f.MENU_ID AND m.IS_DELETED = 0 AND m.MENU_CODE = 'MENU_ANNOUNCEMENT'
      CROSS JOIN SYS_ROLES r
     WHERE r.ROLE_CODE = 'ROLE_ADMIN'
       AND f.IS_DELETED = 0
     GROUP BY r.ID, f.MENU_ID
) s ON (t.ROLE_ID = s.ROLE_ID AND t.MENU_ID = s.MENU_ID)
WHEN MATCHED THEN UPDATE SET t.ALLOWED_FUNCTIONS = s.ALLOWED_FUNCTIONS, t.UPDATED_AT = SYSTIMESTAMP,
                             t.UPDATED_BY = 'V18_2_MIGRATION'
WHEN NOT MATCHED THEN INSERT (ID, ROLE_ID, MENU_ID, ALLOWED_FUNCTIONS, CREATED_BY)
                      VALUES (SEQ_SYS_ROLE_MENU_PERM.NEXTVAL, s.ROLE_ID, s.MENU_ID, s.ALLOWED_FUNCTIONS, 'V18_2_MIGRATION');

MERGE INTO SYS_ROLE_MENU_PERMISSIONS t
USING (
    SELECT r.ID AS ROLE_ID,
           f.MENU_ID,
           LISTAGG(f.FUNCTION_CODE, ',') WITHIN GROUP (ORDER BY f.ID) AS ALLOWED_FUNCTIONS
      FROM SYS_FUNCTIONS f
      JOIN SYS_MENUS m ON m.ID = f.MENU_ID AND m.IS_DELETED = 0 AND m.MENU_CODE = 'MENU_ANNOUNCEMENT'
      CROSS JOIN SYS_ROLES r
     WHERE r.ROLE_CODE = 'ROLE_TEACHER'
       AND f.IS_DELETED = 0
       AND f.FUNCTION_CODE IN ('VIEW', 'CREATE', 'UPDATE', 'PUBLISH')
     GROUP BY r.ID, f.MENU_ID
) s ON (t.ROLE_ID = s.ROLE_ID AND t.MENU_ID = s.MENU_ID)
WHEN MATCHED THEN UPDATE SET t.ALLOWED_FUNCTIONS = s.ALLOWED_FUNCTIONS, t.UPDATED_AT = SYSTIMESTAMP,
                             t.UPDATED_BY = 'V18_2_MIGRATION'
WHEN NOT MATCHED THEN INSERT (ID, ROLE_ID, MENU_ID, ALLOWED_FUNCTIONS, CREATED_BY)
                      VALUES (SEQ_SYS_ROLE_MENU_PERM.NEXTVAL, s.ROLE_ID, s.MENU_ID, s.ALLOWED_FUNCTIONS, 'V18_2_MIGRATION');

PROMPT ============ V18_2.5 Kiem tra sau ============

DECLARE
    V_NAME  SYS_MENUS.MENU_NAME%TYPE;
    V_FUNCS NUMBER;
    V_ADMIN NUMBER;
    V_TEACH NUMBER;
BEGIN
    SELECT MENU_NAME INTO V_NAME
      FROM SYS_MENUS
     WHERE MENU_CODE = 'MENU_ANNOUNCEMENT' AND IS_DELETED = 0;
    IF V_NAME IS NULL OR V_NAME <> UNISTR('Th\00F4ng b\00E1o') THEN
        RAISE_APPLICATION_ERROR(-20004,
            'V18_2: ten menu MENU_ANNOUNCEMENT khong khop UNISTR (kiem tra seed)');
    END IF;

    SELECT COUNT(*) INTO V_FUNCS
      FROM SYS_FUNCTIONS f
      JOIN SYS_MENUS m ON m.ID = f.MENU_ID AND m.MENU_CODE = 'MENU_ANNOUNCEMENT'
     WHERE f.IS_DELETED = 0
       AND f.FUNCTION_CODE IN ('VIEW', 'CREATE', 'UPDATE', 'DELETE', 'PUBLISH');
    IF V_FUNCS <> 5 THEN
        RAISE_APPLICATION_ERROR(-20005, 'V18_2: MENU_ANNOUNCEMENT co ' || V_FUNCS || '/5 chuc nang');
    END IF;

    SELECT COUNT(*) INTO V_ADMIN
      FROM SYS_ROLE_MENU_PERMISSIONS p
      JOIN SYS_MENUS m ON m.ID = p.MENU_ID AND m.MENU_CODE = 'MENU_ANNOUNCEMENT'
      JOIN SYS_ROLES r ON r.ID = p.ROLE_ID AND r.ROLE_CODE = 'ROLE_ADMIN'
     WHERE INSTR(',' || p.ALLOWED_FUNCTIONS || ',', ',VIEW,') > 0
       AND INSTR(',' || p.ALLOWED_FUNCTIONS || ',', ',CREATE,') > 0
       AND INSTR(',' || p.ALLOWED_FUNCTIONS || ',', ',UPDATE,') > 0
       AND INSTR(',' || p.ALLOWED_FUNCTIONS || ',', ',DELETE,') > 0
       AND INSTR(',' || p.ALLOWED_FUNCTIONS || ',', ',PUBLISH,') > 0;
    IF V_ADMIN <> 1 THEN
        RAISE_APPLICATION_ERROR(-20006, 'V18_2: ROLE_ADMIN chua du quyen MENU_ANNOUNCEMENT');
    END IF;

    SELECT COUNT(*) INTO V_TEACH
      FROM SYS_ROLE_MENU_PERMISSIONS p
      JOIN SYS_MENUS m ON m.ID = p.MENU_ID AND m.MENU_CODE = 'MENU_ANNOUNCEMENT'
      JOIN SYS_ROLES r ON r.ID = p.ROLE_ID AND r.ROLE_CODE = 'ROLE_TEACHER'
     WHERE INSTR(',' || p.ALLOWED_FUNCTIONS || ',', ',VIEW,') > 0
       AND INSTR(',' || p.ALLOWED_FUNCTIONS || ',', ',CREATE,') > 0
       AND INSTR(',' || p.ALLOWED_FUNCTIONS || ',', ',UPDATE,') > 0
       AND INSTR(',' || p.ALLOWED_FUNCTIONS || ',', ',PUBLISH,') > 0
       AND INSTR(',' || p.ALLOWED_FUNCTIONS || ',', ',DELETE,') = 0;
    IF V_TEACH <> 1 THEN
        RAISE_APPLICATION_ERROR(-20007, 'V18_2: ROLE_TEACHER chua dung quyen MENU_ANNOUNCEMENT');
    END IF;
    DBMS_OUTPUT.PUT_LINE('  MENU_ANNOUNCEMENT                       OK');
END;
/

COMMIT;

PROMPT ============ V18_2 DONE ============
EXIT
