-- =============================================================================
-- EDUCATION - MIGRATION V3: QUY LUAT SINH MA NGHIEP VU (SYS_CODE_RULES)
--
-- Trigger TRG_EDU_STUDENTS_BI_ID : chi cap ID tu SEQ_EDU_STUDENTS khi NULL.
-- Trigger TRG_EDU_STUDENTS_BI_CODE: sinh STUDENT_CODE theo hang SYS_CODE_RULES
--   (RULE_CODE = STUDENT), KHONG con hard-code yyyyMMddHHmmssXXXX.
--
-- Pattern token: {PREFIX} {YYYY} {YY} {MM} {DD} {SEQ}
-- Vi du mac dinh: PREFIX=SV, PATTERN={PREFIX}{YYYY}{SEQ}, SEQ_LENGTH=4, RESET=YEAR
--   => SV20260001, SV20260002, ...
--
-- Script IDEMPOTENT.
--   sqlplus EDUCATION/EDUCATION@//localhost:1521/ORCL @V3__sys_code_rules.sql
-- =============================================================================

SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED

PROMPT ============ V3.1 Sequence + bang SYS_CODE_RULES ============

DECLARE
    PROCEDURE DDL(P_SQL VARCHAR2) IS
    BEGIN
        EXECUTE IMMEDIATE P_SQL;
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE IN (-955) THEN
                NULL;
            ELSE
                RAISE;
            END IF;
    END DDL;
BEGIN
    DDL(q'[CREATE SEQUENCE SEQ_SYS_CODE_RULES START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE]');
    DDL(q'[
        CREATE TABLE SYS_CODE_RULES (
            ID             NUMBER(19)    NOT NULL,
            RULE_CODE      VARCHAR2(30)  NOT NULL,
            MODULE_NAME    VARCHAR2(30)  NOT NULL,
            TABLE_NAME     VARCHAR2(30)  NOT NULL,
            PREFIX         VARCHAR2(10),
            PATTERN        VARCHAR2(80)  NOT NULL,
            SEQ_LENGTH     NUMBER(2)     DEFAULT 4 NOT NULL,
            RESET_CYCLE    VARCHAR2(10)  DEFAULT 'YEAR' NOT NULL,
            LAST_RESET_KEY VARCHAR2(8),
            LAST_SEQ       NUMBER(10)    DEFAULT 0 NOT NULL,
            IS_ACTIVE      NUMBER(1)     DEFAULT 1 NOT NULL,
            IS_DELETED     NUMBER(1)     DEFAULT 0 NOT NULL,
            CREATED_AT     TIMESTAMP(6)  DEFAULT SYSTIMESTAMP NOT NULL,
            UPDATED_AT     TIMESTAMP(6),
            CREATED_BY     VARCHAR2(50),
            UPDATED_BY     VARCHAR2(50),
            CONSTRAINT PK_SYS_CODE_RULES PRIMARY KEY (ID),
            CONSTRAINT UQ_SYS_CODE_RULES_CODE UNIQUE (RULE_CODE),
            CONSTRAINT CK_CODE_RULES_SEQ_LEN CHECK (SEQ_LENGTH BETWEEN 1 AND 10),
            CONSTRAINT CK_CODE_RULES_RESET CHECK (RESET_CYCLE IN ('NEVER', 'YEAR', 'MONTH', 'DAY')),
            CONSTRAINT CK_CODE_RULES_ACTIVE CHECK (IS_ACTIVE IN (0, 1)),
            CONSTRAINT CK_CODE_RULES_DELETED CHECK (IS_DELETED IN (0, 1))
        )
    ]');
    DBMS_OUTPUT.PUT_LINE('SYS_CODE_RULES: OK');
END;
/

PROMPT ============ V3.2 Function FN_NEXT_BIZ_CODE ============

CREATE OR REPLACE FUNCTION FN_NEXT_BIZ_CODE(P_RULE_CODE IN VARCHAR2)
    RETURN VARCHAR2
IS
    V_PREFIX     VARCHAR2(10);
    V_PATTERN    VARCHAR2(80);
    V_SEQ_LEN    NUMBER(2);
    V_CYCLE      VARCHAR2(10);
    V_RESET_KEY  VARCHAR2(8);
    V_LAST_KEY   VARCHAR2(8);
    V_SEQ        NUMBER(10);
    V_MAX_SEQ    NUMBER(10);
    V_NOW        TIMESTAMP := SYSTIMESTAMP;
    V_CODE       VARCHAR2(30);
BEGIN
    IF P_RULE_CODE IS NULL OR TRIM(P_RULE_CODE) IS NULL THEN
        RAISE_APPLICATION_ERROR(-20011, 'Thieu RULE_CODE khi sinh ma nghiep vu.');
    END IF;

    BEGIN
        SELECT PREFIX, PATTERN, SEQ_LENGTH, RESET_CYCLE, LAST_RESET_KEY, LAST_SEQ
          INTO V_PREFIX, V_PATTERN, V_SEQ_LEN, V_CYCLE, V_LAST_KEY, V_SEQ
          FROM SYS_CODE_RULES
         WHERE RULE_CODE = UPPER(TRIM(P_RULE_CODE))
           AND IS_DELETED = 0
           AND IS_ACTIVE = 1
           FOR UPDATE;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(
                -20012,
                'Khong tim thay quy luat sinh ma active cho RULE_CODE=' || UPPER(TRIM(P_RULE_CODE)));
    END;

    V_RESET_KEY := CASE V_CYCLE
                       WHEN 'YEAR'  THEN TO_CHAR(V_NOW, 'YYYY')
                       WHEN 'MONTH' THEN TO_CHAR(V_NOW, 'YYYYMM')
                       WHEN 'DAY'   THEN TO_CHAR(V_NOW, 'YYYYMMDD')
                       ELSE '*'
                   END;

    IF V_LAST_KEY IS NULL OR V_LAST_KEY <> V_RESET_KEY THEN
        V_SEQ := 0;
    END IF;

    V_SEQ := V_SEQ + 1;
    V_MAX_SEQ := POWER(10, V_SEQ_LEN) - 1;
    IF V_SEQ > V_MAX_SEQ THEN
        RAISE_APPLICATION_ERROR(
            -20013,
            'Da vuot so thu tu toi da ' || V_MAX_SEQ || ' cua quy luat ' || UPPER(TRIM(P_RULE_CODE)));
    END IF;

    V_CODE := V_PATTERN;
    V_CODE := REPLACE(V_CODE, '{PREFIX}', NVL(V_PREFIX, ''));
    V_CODE := REPLACE(V_CODE, '{YYYY}', TO_CHAR(V_NOW, 'YYYY'));
    V_CODE := REPLACE(V_CODE, '{YY}', TO_CHAR(V_NOW, 'YY'));
    V_CODE := REPLACE(V_CODE, '{MM}', TO_CHAR(V_NOW, 'MM'));
    V_CODE := REPLACE(V_CODE, '{DD}', TO_CHAR(V_NOW, 'DD'));
    V_CODE := REPLACE(V_CODE, '{SEQ}', LPAD(TO_CHAR(V_SEQ), V_SEQ_LEN, '0'));

    IF LENGTH(V_CODE) > 30 THEN
        RAISE_APPLICATION_ERROR(-20014, 'Ma sinh ra vuot 30 ky tu: ' || V_CODE);
    END IF;

    UPDATE SYS_CODE_RULES
       SET LAST_SEQ       = V_SEQ,
           LAST_RESET_KEY = V_RESET_KEY,
           UPDATED_AT     = V_NOW
     WHERE RULE_CODE = UPPER(TRIM(P_RULE_CODE))
       AND IS_DELETED = 0
       AND IS_ACTIVE = 1;

    RETURN V_CODE;
END FN_NEXT_BIZ_CODE;
/

PROMPT FN_NEXT_BIZ_CODE: OK

PROMPT ============ V3.3 Seed quy luat STUDENT ============

MERGE INTO SYS_CODE_RULES t
USING (
    SELECT
        'STUDENT' AS RULE_CODE,
        'STUDENT' AS MODULE_NAME,
        'EDU_STUDENTS' AS TABLE_NAME,
        'SV' AS PREFIX,
        '{PREFIX}{YYYY}{SEQ}' AS PATTERN,
        4 AS SEQ_LENGTH,
        'YEAR' AS RESET_CYCLE
    FROM DUAL
) s
ON (t.RULE_CODE = s.RULE_CODE)
WHEN NOT MATCHED THEN
    INSERT (ID, RULE_CODE, MODULE_NAME, TABLE_NAME, PREFIX, PATTERN, SEQ_LENGTH,
            RESET_CYCLE, LAST_RESET_KEY, LAST_SEQ, IS_ACTIVE, IS_DELETED, CREATED_AT)
    VALUES (SEQ_SYS_CODE_RULES.NEXTVAL, s.RULE_CODE, s.MODULE_NAME, s.TABLE_NAME, s.PREFIX,
            s.PATTERN, s.SEQ_LENGTH, s.RESET_CYCLE, TO_CHAR(SYSDATE, 'YYYY'), 0, 1, 0, SYSTIMESTAMP)
WHEN MATCHED THEN
    UPDATE SET t.MODULE_NAME = s.MODULE_NAME,
               t.TABLE_NAME  = s.TABLE_NAME,
               t.IS_ACTIVE   = 1,
               t.IS_DELETED  = 0,
               t.UPDATED_AT  = SYSTIMESTAMP;

-- Dong bo LAST_SEQ voi ma SV{YYYY}xxxx da co (neu dung dinh dang moi).
DECLARE
    V_YEAR VARCHAR2(4) := TO_CHAR(SYSDATE, 'YYYY');
    V_MAX  NUMBER;
BEGIN
    SELECT NVL(MAX(TO_NUMBER(SUBSTR(STUDENT_CODE, -4))), 0)
      INTO V_MAX
      FROM EDU_STUDENTS
     WHERE REGEXP_LIKE(STUDENT_CODE, '^SV' || V_YEAR || '[0-9]{4}$');

    UPDATE SYS_CODE_RULES
       SET LAST_SEQ       = GREATEST(NVL(LAST_SEQ, 0), V_MAX),
           LAST_RESET_KEY = V_YEAR,
           UPDATED_AT     = SYSTIMESTAMP
     WHERE RULE_CODE = 'STUDENT';

    DBMS_OUTPUT.PUT_LINE('STUDENT rule LAST_SEQ=' || V_MAX || ' YEAR=' || V_YEAR);
END;
/

PROMPT ============ V3.4 Trigger ID + Trigger ma hoc sinh theo quy luat ============

CREATE OR REPLACE TRIGGER TRG_EDU_STUDENTS_BI_ID
BEFORE INSERT ON EDU_STUDENTS
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT SEQ_EDU_STUDENTS.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_EDU_STUDENTS_BI_CODE
BEFORE INSERT ON EDU_STUDENTS
FOR EACH ROW
FOLLOWS TRG_EDU_STUDENTS_BI_ID
BEGIN
    :NEW.STUDENT_CODE := FN_NEXT_BIZ_CODE('STUDENT');
END;
/

PROMPT Triggers: OK

COLUMN STATUS FORMAT A10
COLUMN TRIGGER_NAME FORMAT A32
SELECT TRIGGER_NAME, STATUS, TRIGGERING_EVENT
  FROM USER_TRIGGERS
 WHERE TRIGGER_NAME IN ('TRG_EDU_STUDENTS_BI_ID', 'TRG_EDU_STUDENTS_BI_CODE')
 ORDER BY TRIGGER_NAME;

SELECT RULE_CODE, PREFIX, PATTERN, SEQ_LENGTH, RESET_CYCLE, LAST_RESET_KEY, LAST_SEQ, IS_ACTIVE
  FROM SYS_CODE_RULES
 WHERE RULE_CODE = 'STUDENT';

PROMPT ============ V3 HOAN TAT ============
PROMPT ID: trigger TRG_EDU_STUDENTS_BI_ID (SEQ_EDU_STUDENTS).
PROMPT STUDENT_CODE: FN_NEXT_BIZ_CODE doc SYS_CODE_RULES (mac dinh SV+YYYY+0001).

EXIT;

