-- =============================================================================
-- EDUCATION - MIGRATION V4: SINH MA LOP HOC THEO SYS_CODE_RULES
--
-- Trigger TRG_EDU_CLASSES_BI_ID  : chi cap ID tu SEQ_EDU_CLASSES khi NULL.
-- Trigger TRG_EDU_CLASSES_BI_CODE: sinh CLASS_CODE theo hang SYS_CODE_RULES
--   (RULE_CODE = CLASS) qua FN_NEXT_BIZ_CODE.
--
-- Mac dinh: PREFIX=LH, PATTERN={PREFIX}{YYYY}{SEQ}, SEQ_LENGTH=4, RESET=YEAR
--   => LH20260001, LH20260002, ...
--
-- Script IDEMPOTENT.
--   sqlplus EDUCATION/EDUCATION@//localhost:1521/ORCL @V4__sys_code_rules_class.sql
-- =============================================================================

SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED

PROMPT ============ V4.1 Seed quy luat CLASS ============

MERGE INTO SYS_CODE_RULES t
USING (
    SELECT
        'CLASS' AS RULE_CODE,
        'CLASS' AS MODULE_NAME,
        'EDU_CLASSES' AS TABLE_NAME,
        'LH' AS PREFIX,
        '{PREFIX}{YYYY}{SEQ}' AS PATTERN,
        4 AS SEQ_LENGTH,
        'YEAR' AS RESET_CYCLE
    FROM DUAL
) s
ON (t.RULE_CODE = s.RULE_CODE)
WHEN NOT MATCHED THEN
    INSERT (ID, RULE_CODE, MODULE_NAME, TABLE_NAME, PREFIX, PATTERN, SEQ_LENGTH,
            RESET_CYCLE, LAST_RESET_KEY, LAST_SEQ, IS_ACTIVE, IS_DELETED, CREATED_AT)
    VALUES (SEQ_SYS_CODE_RULES.NEXTVAL, s.RULE_CODE, s.MODULE_NAME, s.TABLE_NAME, s.PREFIX,
            s.PATTERN, s.SEQ_LENGTH, s.RESET_CYCLE, TO_CHAR(SYSDATE, 'YYYY'), 0, 1, 0, SYSTIMESTAMP)
WHEN MATCHED THEN
    UPDATE SET t.MODULE_NAME = s.MODULE_NAME,
               t.TABLE_NAME  = s.TABLE_NAME,
               t.IS_ACTIVE   = 1,
               t.IS_DELETED  = 0,
               t.UPDATED_AT  = SYSTIMESTAMP;

DECLARE
    V_YEAR VARCHAR2(4) := TO_CHAR(SYSDATE, 'YYYY');
    V_MAX  NUMBER;
BEGIN
    SELECT NVL(MAX(TO_NUMBER(SUBSTR(CLASS_CODE, -4))), 0)
      INTO V_MAX
      FROM EDU_CLASSES
     WHERE REGEXP_LIKE(CLASS_CODE, '^LH' || V_YEAR || '[0-9]{4}$');

    UPDATE SYS_CODE_RULES
       SET LAST_SEQ       = GREATEST(NVL(LAST_SEQ, 0), V_MAX),
           LAST_RESET_KEY = V_YEAR,
           UPDATED_AT     = SYSTIMESTAMP
     WHERE RULE_CODE = 'CLASS';

    DBMS_OUTPUT.PUT_LINE('CLASS rule LAST_SEQ=' || V_MAX || ' YEAR=' || V_YEAR);
END;
/

PROMPT ============ V4.2 Trigger ID + Trigger ma lop theo quy luat ============

CREATE OR REPLACE TRIGGER TRG_EDU_CLASSES_BI_ID
BEFORE INSERT ON EDU_CLASSES
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT SEQ_EDU_CLASSES.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_EDU_CLASSES_BI_CODE
BEFORE INSERT ON EDU_CLASSES
FOR EACH ROW
FOLLOWS TRG_EDU_CLASSES_BI_ID
BEGIN
    :NEW.CLASS_CODE := FN_NEXT_BIZ_CODE('CLASS');
END;
/

PROMPT Triggers: OK

COLUMN STATUS FORMAT A10
COLUMN TRIGGER_NAME FORMAT A32
SELECT TRIGGER_NAME, STATUS, TRIGGERING_EVENT
  FROM USER_TRIGGERS
 WHERE TRIGGER_NAME IN ('TRG_EDU_CLASSES_BI_ID', 'TRG_EDU_CLASSES_BI_CODE')
 ORDER BY TRIGGER_NAME;

SELECT RULE_CODE, PREFIX, PATTERN, SEQ_LENGTH, RESET_CYCLE, LAST_RESET_KEY, LAST_SEQ, IS_ACTIVE
  FROM SYS_CODE_RULES
 WHERE RULE_CODE IN ('STUDENT', 'CLASS')
 ORDER BY RULE_CODE;

PROMPT ============ V4 HOAN TAT ============
PROMPT ID: trigger TRG_EDU_CLASSES_BI_ID (SEQ_EDU_CLASSES).
PROMPT CLASS_CODE: FN_NEXT_BIZ_CODE doc SYS_CODE_RULES (mac dinh LH+YYYY+0001).

EXIT;
