-- =============================================================================
-- EDUCATION - MIGRATION V6: QUAN LY LICH HOC & THOI KHOA BIEU
--
-- EDU_CLASS_SCHEDULES : khung lich tuan (thu 2-8, gio HH:mm)
-- EDU_CLASS_SESSIONS  : buoi hoc thuc te theo ngay
-- PRC_GET_TIMETABLE_BY_RANGE : ref cursor lich theo khoang ngay
-- Menu MENU_TIMETABLE (DIR_ACADEMIC) + functions VIEW/CONFIG_SCHEDULE/
--   GENERATE_SESSIONS/CANCEL_SESSION
--
--   sqlplus EDUCATION/EDUCATION@//localhost:1521/ORCL @V6__class_timetable.sql
-- =============================================================================

SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED

PROMPT ============ V6.1 Sequences ============

BEGIN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_EDU_CLASS_SCHEDULES START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE';
    DBMS_OUTPUT.PUT_LINE('SEQ_EDU_CLASS_SCHEDULES: created');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            DBMS_OUTPUT.PUT_LINE('SEQ_EDU_CLASS_SCHEDULES: already exists');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_EDU_CLASS_SESSIONS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE';
    DBMS_OUTPUT.PUT_LINE('SEQ_EDU_CLASS_SESSIONS: created');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            DBMS_OUTPUT.PUT_LINE('SEQ_EDU_CLASS_SESSIONS: already exists');
        ELSE
            RAISE;
        END IF;
END;
/

PROMPT ============ V6.2 EDU_CLASS_SCHEDULES ============

BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE EDU_CLASS_SCHEDULES (
            ID           NUMBER(19)    NOT NULL,
            CLASS_ID     NUMBER(19)    NOT NULL,
            DAY_OF_WEEK  NUMBER(1)     NOT NULL,
            START_TIME   VARCHAR2(5)   NOT NULL,
            END_TIME     VARCHAR2(5)   NOT NULL,
            ROOM_NAME    VARCHAR2(50),
            TEACHER_ID   NUMBER(19),
            STATUS       VARCHAR2(20)  DEFAULT 'ACTIVE' NOT NULL,
            IS_DELETED   NUMBER(1)     DEFAULT 0 NOT NULL,
            CREATED_AT   TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP NOT NULL,
            UPDATED_AT   TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP,
            CREATED_BY   VARCHAR2(50),
            UPDATED_BY   VARCHAR2(50),
            CONSTRAINT PK_EDU_CLASS_SCHEDULES PRIMARY KEY (ID),
            CONSTRAINT FK_SCHEDULES_CLASS FOREIGN KEY (CLASS_ID) REFERENCES EDU_CLASSES (ID),
            CONSTRAINT FK_SCHEDULES_TEACHER FOREIGN KEY (TEACHER_ID) REFERENCES SYS_USERS (ID),
            CONSTRAINT CK_SCHEDULES_DOW CHECK (DAY_OF_WEEK BETWEEN 2 AND 8),
            CONSTRAINT CK_SCHEDULES_START CHECK (REGEXP_LIKE(START_TIME, '^([01][0-9]|2[0-3]):[0-5][0-9]$')),
            CONSTRAINT CK_SCHEDULES_END CHECK (REGEXP_LIKE(END_TIME, '^([01][0-9]|2[0-3]):[0-5][0-9]$')),
            CONSTRAINT CK_SCHEDULES_PERIOD CHECK (START_TIME < END_TIME),
            CONSTRAINT CK_SCHEDULES_STATUS CHECK (STATUS IN ('ACTIVE', 'INACTIVE')),
            CONSTRAINT CK_SCHEDULES_DELETED CHECK (IS_DELETED IN (0, 1))
        )
    ]';
    DBMS_OUTPUT.PUT_LINE('EDU_CLASS_SCHEDULES: created');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            DBMS_OUTPUT.PUT_LINE('EDU_CLASS_SCHEDULES: already exists');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IX_SCHEDULES_CLASS ON EDU_CLASS_SCHEDULES (CLASS_ID, DAY_OF_WEEK, IS_DELETED)';
    DBMS_OUTPUT.PUT_LINE('IX_SCHEDULES_CLASS: OK');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE IN (-955, -1408) THEN
            DBMS_OUTPUT.PUT_LINE('IX_SCHEDULES_CLASS: already exists');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IX_SCHEDULES_TEACHER ON EDU_CLASS_SCHEDULES (TEACHER_ID, DAY_OF_WEEK, IS_DELETED)';
    DBMS_OUTPUT.PUT_LINE('IX_SCHEDULES_TEACHER: OK');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE IN (-955, -1408) THEN
            DBMS_OUTPUT.PUT_LINE('IX_SCHEDULES_TEACHER: already exists');
        ELSE
            RAISE;
        END IF;
END;
/

PROMPT ============ V6.3 EDU_CLASS_SESSIONS ============

BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE EDU_CLASS_SESSIONS (
            ID            NUMBER(19)    NOT NULL,
            CLASS_ID      NUMBER(19)    NOT NULL,
            SCHEDULE_ID   NUMBER(19),
            SESSION_DATE  DATE          NOT NULL,
            START_TIME    VARCHAR2(5)   NOT NULL,
            END_TIME      VARCHAR2(5)   NOT NULL,
            ROOM_NAME     VARCHAR2(50),
            TEACHER_ID    NUMBER(19),
            TOPIC         VARCHAR2(200),
            STATUS        VARCHAR2(20)  DEFAULT 'SCHEDULED' NOT NULL,
            NOTE          VARCHAR2(500),
            IS_DELETED    NUMBER(1)     DEFAULT 0 NOT NULL,
            CREATED_AT    TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP NOT NULL,
            UPDATED_AT    TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP,
            CREATED_BY    VARCHAR2(50),
            UPDATED_BY    VARCHAR2(50),
            CONSTRAINT PK_EDU_CLASS_SESSIONS PRIMARY KEY (ID),
            CONSTRAINT FK_SESSIONS_CLASS FOREIGN KEY (CLASS_ID) REFERENCES EDU_CLASSES (ID),
            CONSTRAINT FK_SESSIONS_SCHEDULE FOREIGN KEY (SCHEDULE_ID) REFERENCES EDU_CLASS_SCHEDULES (ID),
            CONSTRAINT FK_SESSIONS_TEACHER FOREIGN KEY (TEACHER_ID) REFERENCES SYS_USERS (ID),
            CONSTRAINT CK_SESSIONS_START CHECK (REGEXP_LIKE(START_TIME, '^([01][0-9]|2[0-3]):[0-5][0-9]$')),
            CONSTRAINT CK_SESSIONS_END CHECK (REGEXP_LIKE(END_TIME, '^([01][0-9]|2[0-3]):[0-5][0-9]$')),
            CONSTRAINT CK_SESSIONS_PERIOD CHECK (START_TIME < END_TIME),
            CONSTRAINT CK_SESSIONS_STATUS CHECK (STATUS IN ('SCHEDULED', 'COMPLETED', 'CANCELLED')),
            CONSTRAINT CK_SESSIONS_DELETED CHECK (IS_DELETED IN (0, 1))
        )
    ]';
    DBMS_OUTPUT.PUT_LINE('EDU_CLASS_SESSIONS: created');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            DBMS_OUTPUT.PUT_LINE('EDU_CLASS_SESSIONS: already exists');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IX_SESSIONS_CLASS_DATE ON EDU_CLASS_SESSIONS (CLASS_ID, SESSION_DATE, IS_DELETED)';
    DBMS_OUTPUT.PUT_LINE('IX_SESSIONS_CLASS_DATE: OK');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE IN (-955, -1408) THEN
            DBMS_OUTPUT.PUT_LINE('IX_SESSIONS_CLASS_DATE: already exists');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IX_SESSIONS_TEACHER_DATE ON EDU_CLASS_SESSIONS (TEACHER_ID, SESSION_DATE, IS_DELETED)';
    DBMS_OUTPUT.PUT_LINE('IX_SESSIONS_TEACHER_DATE: OK');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE IN (-955, -1408) THEN
            DBMS_OUTPUT.PUT_LINE('IX_SESSIONS_TEACHER_DATE: already exists');
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IX_SESSIONS_ROOM_DATE ON EDU_CLASS_SESSIONS (ROOM_NAME, SESSION_DATE, IS_DELETED)';
    DBMS_OUTPUT.PUT_LINE('IX_SESSIONS_ROOM_DATE: OK');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE IN (-955, -1408) THEN
            DBMS_OUTPUT.PUT_LINE('IX_SESSIONS_ROOM_DATE: already exists');
        ELSE
            RAISE;
        END IF;
END;
/

PROMPT ============ V6.4 PRC_GET_TIMETABLE_BY_RANGE ============

CREATE OR REPLACE PROCEDURE PRC_GET_TIMETABLE_BY_RANGE(
    P_FROM_DATE   IN  DATE,
    P_TO_DATE     IN  DATE,
    P_CLASS_ID    IN  NUMBER,
    P_TEACHER_ID  IN  NUMBER,
    P_STUDENT_ID  IN  NUMBER,
    O_CURSOR      OUT SYS_REFCURSOR,
    O_ERR_CODE    OUT VARCHAR2,
    O_ERR_MSG     OUT VARCHAR2
) AS
    V_FROM DATE;
    V_TO   DATE;
    -- American 'D': 1=Sunday ... 7=Saturday. Quy uoc he thong: 2=Thu Hai ... 8=Chu Nhat.
BEGIN
    IF P_FROM_DATE IS NULL OR P_TO_DATE IS NULL THEN
        O_ERR_CODE := 'INVALID_DATE_RANGE';
        O_ERR_MSG  := 'Tu ngay va den ngay khong duoc de trong.';
        RETURN;
    END IF;

    V_FROM := TRUNC(P_FROM_DATE);
    V_TO   := TRUNC(P_TO_DATE);
    IF V_TO < V_FROM THEN
        O_ERR_CODE := 'INVALID_DATE_RANGE';
        O_ERR_MSG  := 'Den ngay khong duoc nho hon tu ngay.';
        RETURN;
    END IF;

    OPEN O_CURSOR FOR
        SELECT s.ID,
               s.CLASS_ID,
               c.CLASS_CODE,
               c.CLASS_NAME,
               s.SCHEDULE_ID,
               s.SESSION_DATE,
               CASE TO_NUMBER(TO_CHAR(s.SESSION_DATE, 'D', 'NLS_DATE_LANGUAGE=AMERICAN'))
                   WHEN 1 THEN 8
                   ELSE TO_NUMBER(TO_CHAR(s.SESSION_DATE, 'D', 'NLS_DATE_LANGUAGE=AMERICAN'))
               END AS DAY_OF_WEEK,
               s.START_TIME,
               s.END_TIME,
               s.ROOM_NAME,
               s.TEACHER_ID,
               u.FULL_NAME AS TEACHER_NAME,
               s.TOPIC,
               s.STATUS,
               s.NOTE
          FROM EDU_CLASS_SESSIONS s
          JOIN EDU_CLASSES c ON c.ID = s.CLASS_ID
          LEFT JOIN SYS_USERS u ON u.ID = s.TEACHER_ID
         WHERE s.IS_DELETED = 0
           AND s.SESSION_DATE BETWEEN V_FROM AND V_TO
           AND (P_CLASS_ID IS NULL OR s.CLASS_ID = P_CLASS_ID)
           AND (P_TEACHER_ID IS NULL OR s.TEACHER_ID = P_TEACHER_ID)
           AND (P_STUDENT_ID IS NULL OR EXISTS (
                    SELECT 1
                      FROM EDU_CLASS_STUDENTS cs
                     WHERE cs.CLASS_ID = s.CLASS_ID
                       AND cs.STUDENT_ID = P_STUDENT_ID
                       AND cs.IS_DELETED = 0
                       AND cs.STATUS = 'ENROLLED'))
         ORDER BY s.SESSION_DATE, s.START_TIME, s.CLASS_ID;

    O_ERR_CODE := '0';
    O_ERR_MSG  := 'SUCCESS';
EXCEPTION
    WHEN OTHERS THEN
        IF O_CURSOR IS NOT NULL AND O_CURSOR%ISOPEN THEN CLOSE O_CURSOR; END IF;
        O_ERR_CODE := TO_CHAR(SQLCODE);
        O_ERR_MSG  := SUBSTR(SQLERRM, 1, 255);
END PRC_GET_TIMETABLE_BY_RANGE;
/

PROMPT PRC_GET_TIMETABLE_BY_RANGE: OK

PROMPT ============ V6.5 Menu MENU_TIMETABLE + functions + quyen ============

MERGE INTO SYS_MENUS t
USING (
    SELECT 105 ID, 100 PARENT_ID, 'MENU_TIMETABLE' MENU_CODE,
           'Lịch học & TKB' MENU_NAME, '/academic/timetable' PATH,
           'calendar' ICON, 5 SORT_ORDER
      FROM DUAL
) s ON (t.MENU_CODE = s.MENU_CODE)
WHEN MATCHED THEN UPDATE SET
    t.PARENT_ID = s.PARENT_ID,
    t.MENU_NAME = s.MENU_NAME,
    t.PATH = s.PATH,
    t.ICON = s.ICON,
    t.SORT_ORDER = s.SORT_ORDER,
    t.MENU_TYPE = 'MENU',
    t.STATUS = 'ACTIVE',
    t.IS_DELETED = 0
WHEN NOT MATCHED THEN INSERT (
    ID, PARENT_ID, MENU_CODE, MENU_NAME, MENU_TYPE, PATH, ICON, SORT_ORDER,
    IS_HIDDEN, STATUS, IS_DELETED, CREATED_BY)
VALUES (
    s.ID, s.PARENT_ID, s.MENU_CODE, s.MENU_NAME, 'MENU', s.PATH, s.ICON, s.SORT_ORDER,
    0, 'ACTIVE', 0, 'V6_MIGRATION');

MERGE INTO SYS_FUNCTIONS t
USING (
    SELECT m.ID AS MENU_ID,
           x.FUNCTION_CODE,
           CASE x.FUNCTION_CODE
               WHEN 'VIEW'               THEN 'Xem thời khóa biểu'
               WHEN 'CONFIG_SCHEDULE'    THEN 'Cấu hình lịch tuần'
               WHEN 'GENERATE_SESSIONS'  THEN 'Sinh buổi học'
               WHEN 'CANCEL_SESSION'     THEN 'Hủy buổi học'
               ELSE x.FUNCTION_CODE
           END AS FUNCTION_NAME
      FROM SYS_MENUS m
      JOIN (
            SELECT 'MENU_TIMETABLE' MENU_CODE, 'VIEW'              FUNCTION_CODE FROM DUAL UNION ALL
            SELECT 'MENU_TIMETABLE'           , 'CONFIG_SCHEDULE'                FROM DUAL UNION ALL
            SELECT 'MENU_TIMETABLE'           , 'GENERATE_SESSIONS'              FROM DUAL UNION ALL
            SELECT 'MENU_TIMETABLE'           , 'CANCEL_SESSION'                 FROM DUAL
           ) x ON x.MENU_CODE = m.MENU_CODE
) s ON (t.MENU_ID = s.MENU_ID AND t.FUNCTION_CODE = s.FUNCTION_CODE)
WHEN MATCHED THEN UPDATE SET t.FUNCTION_NAME = s.FUNCTION_NAME, t.IS_DELETED = 0
WHEN NOT MATCHED THEN INSERT (ID, MENU_ID, FUNCTION_CODE, FUNCTION_NAME, IS_DELETED)
                      VALUES (SEQ_SYS_FUNCTIONS.NEXTVAL, s.MENU_ID, s.FUNCTION_CODE, s.FUNCTION_NAME, 0);

MERGE INTO SYS_ROLE_MENU_PERMISSIONS t
USING (
    SELECT r.ID AS ROLE_ID,
           m.ID AS MENU_ID,
           LISTAGG(f.FUNCTION_CODE, ',') WITHIN GROUP (ORDER BY f.FUNCTION_CODE) AS ALLOWED_FUNCTIONS
      FROM SYS_ROLES r
      JOIN SYS_MENUS m ON m.MENU_CODE = 'MENU_TIMETABLE' AND m.IS_DELETED = 0
      JOIN SYS_FUNCTIONS f ON f.MENU_ID = m.ID AND f.IS_DELETED = 0
     WHERE r.ROLE_CODE = 'ROLE_ADMIN'
       AND r.IS_DELETED = 0
     GROUP BY r.ID, m.ID
) s ON (t.ROLE_ID = s.ROLE_ID AND t.MENU_ID = s.MENU_ID)
WHEN MATCHED THEN UPDATE SET t.ALLOWED_FUNCTIONS = s.ALLOWED_FUNCTIONS
WHEN NOT MATCHED THEN INSERT (ID, ROLE_ID, MENU_ID, ALLOWED_FUNCTIONS, CREATED_BY)
                      VALUES (SEQ_SYS_ROLE_MENU_PERM.NEXTVAL, s.ROLE_ID, s.MENU_ID, s.ALLOWED_FUNCTIONS, 'V6_MIGRATION');

MERGE INTO SYS_ROLE_MENU_PERMISSIONS t
USING (
    SELECT r.ID AS ROLE_ID, m.ID AS MENU_ID, x.ALLOWED_FUNCTIONS
      FROM SYS_ROLES r
      JOIN SYS_MENUS m ON m.MENU_CODE = 'MENU_TIMETABLE' AND m.IS_DELETED = 0
      JOIN (
            SELECT 'ROLE_TEACHER' ROLE_CODE,
                   'VIEW,CONFIG_SCHEDULE,GENERATE_SESSIONS,CANCEL_SESSION' ALLOWED_FUNCTIONS
              FROM DUAL
           ) x ON x.ROLE_CODE = r.ROLE_CODE
     WHERE r.IS_DELETED = 0
) s ON (t.ROLE_ID = s.ROLE_ID AND t.MENU_ID = s.MENU_ID)
WHEN MATCHED THEN UPDATE SET t.ALLOWED_FUNCTIONS = s.ALLOWED_FUNCTIONS
WHEN NOT MATCHED THEN INSERT (ID, ROLE_ID, MENU_ID, ALLOWED_FUNCTIONS, CREATED_BY)
                      VALUES (SEQ_SYS_ROLE_MENU_PERM.NEXTVAL, s.ROLE_ID, s.MENU_ID, s.ALLOWED_FUNCTIONS, 'V6_MIGRATION');

PROMPT MENU_TIMETABLE: OK

PROMPT ============ V6 HOAN TAT ============
PROMPT Thu 2-8 (Thu Hai..Chu Nhat). Gio HH:mm. Conflict phong/GV xu ly o Service.

EXIT;
