-- =============================================================================
-- EDUCATION - MIGRATION V8: IMPORT HOC SINH TU EXCEL
--
-- 1. Trigger TRG_EDU_STUDENTS_BI_CODE chi sinh ma khi STUDENT_CODE NULL
--    (import hang loat giu nguyen ma trong file Excel).
-- 2. Quyen IMPORT cho MENU_STUDENT_LIST.
--    ROLE_ADMIN: tat ca function cua menu.
--    ROLE_ADMISSION: VIEW,CREATE,IMPORT.
--
--   sqlplus EDUCATION/EDUCATION@//localhost:1521/ORCL @V8__student_excel_import.sql
-- =============================================================================

SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED

PROMPT ============ V8.1 Trigger giu STUDENT_CODE khi da co ============

CREATE OR REPLACE TRIGGER TRG_EDU_STUDENTS_BI_CODE
BEFORE INSERT ON EDU_STUDENTS
FOR EACH ROW
FOLLOWS TRG_EDU_STUDENTS_BI_ID
BEGIN
    IF :NEW.STUDENT_CODE IS NULL OR TRIM(:NEW.STUDENT_CODE) IS NULL THEN
        :NEW.STUDENT_CODE := FN_NEXT_BIZ_CODE('STUDENT');
    ELSE
        :NEW.STUDENT_CODE := TRIM(:NEW.STUDENT_CODE);
    END IF;
END;
/

PROMPT Trigger TRG_EDU_STUDENTS_BI_CODE: OK

PROMPT ============ V8.2 Quyen IMPORT MENU_STUDENT_LIST ============

MERGE INTO SYS_FUNCTIONS t
USING (
    SELECT m.ID AS MENU_ID,
           'IMPORT' AS FUNCTION_CODE,
           N'Import danh sách học sinh' AS FUNCTION_NAME
      FROM SYS_MENUS m
     WHERE m.MENU_CODE = 'MENU_STUDENT_LIST'
       AND m.IS_DELETED = 0
) s ON (t.MENU_ID = s.MENU_ID AND t.FUNCTION_CODE = s.FUNCTION_CODE)
WHEN MATCHED THEN UPDATE SET t.FUNCTION_NAME = s.FUNCTION_NAME, t.IS_DELETED = 0
WHEN NOT MATCHED THEN INSERT (ID, MENU_ID, FUNCTION_CODE, FUNCTION_NAME, IS_DELETED)
                      VALUES (SEQ_SYS_FUNCTIONS.NEXTVAL, s.MENU_ID, s.FUNCTION_CODE, N'Import danh sách học sinh', 0);

MERGE INTO SYS_ROLE_MENU_PERMISSIONS t
USING (
    SELECT r.ID AS ROLE_ID,
           f.MENU_ID,
           LISTAGG(f.FUNCTION_CODE, ',') WITHIN GROUP (ORDER BY f.FUNCTION_CODE) AS ALLOWED_FUNCTIONS
      FROM SYS_FUNCTIONS f
      JOIN SYS_MENUS m ON m.ID = f.MENU_ID AND m.MENU_CODE = 'MENU_STUDENT_LIST' AND m.IS_DELETED = 0
      CROSS JOIN SYS_ROLES r
     WHERE r.ROLE_CODE = 'ROLE_ADMIN'
       AND r.IS_DELETED = 0
       AND f.IS_DELETED = 0
     GROUP BY r.ID, f.MENU_ID
) s ON (t.ROLE_ID = s.ROLE_ID AND t.MENU_ID = s.MENU_ID)
WHEN MATCHED THEN UPDATE SET t.ALLOWED_FUNCTIONS = s.ALLOWED_FUNCTIONS
WHEN NOT MATCHED THEN INSERT (ID, ROLE_ID, MENU_ID, ALLOWED_FUNCTIONS, CREATED_BY)
                      VALUES (SEQ_SYS_ROLE_MENU_PERM.NEXTVAL, s.ROLE_ID, s.MENU_ID, s.ALLOWED_FUNCTIONS, 'V8_MIGRATION');

MERGE INTO SYS_ROLE_MENU_PERMISSIONS t
USING (
    SELECT r.ID AS ROLE_ID, m.ID AS MENU_ID, 'VIEW,CREATE,IMPORT' AS ALLOWED_FUNCTIONS
      FROM SYS_ROLES r
      JOIN SYS_MENUS m ON m.MENU_CODE = 'MENU_STUDENT_LIST' AND m.IS_DELETED = 0
     WHERE r.ROLE_CODE = 'ROLE_ADMISSION'
       AND r.IS_DELETED = 0
) s ON (t.ROLE_ID = s.ROLE_ID AND t.MENU_ID = s.MENU_ID)
WHEN MATCHED THEN UPDATE SET t.ALLOWED_FUNCTIONS = s.ALLOWED_FUNCTIONS
WHEN NOT MATCHED THEN INSERT (ID, ROLE_ID, MENU_ID, ALLOWED_FUNCTIONS, CREATED_BY)
                      VALUES (SEQ_SYS_ROLE_MENU_PERM.NEXTVAL, s.ROLE_ID, s.MENU_ID, s.ALLOWED_FUNCTIONS, 'V8_MIGRATION');

PROMPT ============ V8.3 Kiem tra ============

COLUMN TRIGGER_NAME FORMAT A32
COLUMN STATUS FORMAT A10
SELECT TRIGGER_NAME, STATUS
  FROM USER_TRIGGERS
 WHERE TRIGGER_NAME = 'TRG_EDU_STUDENTS_BI_CODE';

COLUMN FUNCTION_CODE FORMAT A12
COLUMN FUNCTION_NAME FORMAT A40
SELECT f.FUNCTION_CODE, f.FUNCTION_NAME
  FROM SYS_FUNCTIONS f
  JOIN SYS_MENUS m ON m.ID = f.MENU_ID
 WHERE m.MENU_CODE = 'MENU_STUDENT_LIST'
   AND f.IS_DELETED = 0
 ORDER BY f.FUNCTION_CODE;

COMMIT;

PROMPT ============ V8 student excel import: OK ============
